owner: voxel51
repo: upptime
sites:
  - name: voxel51.com
    url: https://voxel51.com
  - name: fiftyone.ai
    url: https://fiftyone.ai
  - name: www.voxel51.com
    url: http://www.voxel51.com
  - name: voxel51.fiftyone.ai
    url: https://voxel51.fiftyone.ai
  - name: docs.voxel51.com
    url: https://docs.voxel51.com
  - name: pypi.fiftyone.ai
    url: https://pypi.fiftyone.ai
    expectedStatusCodes:
      - 401
  - name: pypi.voxel51.com
    url: https://pypi.voxel51.com
assignees:
  - findtopher
status-website:
  cname: upptime.voxel51.com
  logoUrl: https://voxel51.com/images/logo/voxel51-logo-horz-color-600dpi.png
  name: Upptime
  introTitle: "**fiftyone** is the open-source tool for building high-quality datasets and computer vision models."
  introMessage: "This is the [Upptime](https://github.com/upptime/upptime) status page for (Voxel51)(https://voxel51.com)."
  navbar:
    - title: Status
      href: /
    - title: FiftyOne
      href: https://github.com/voxel51/fiftyone
    - title: Voxel51
      href: https://voxel51.com
